resources:
- clusterrole-cert-manager-cainjector.yaml
- clusterrole-cert-manager-cluster-view.yaml
- clusterrole-cert-manager-controller-approve:cert-manager-io.yaml
- clusterrole-cert-manager-controller-certificates.yaml
- clusterrole-cert-manager-controller-certificatesigningrequests.yaml
- clusterrole-cert-manager-controller-challenges.yaml
- clusterrole-cert-manager-controller-clusterissuers.yaml
- clusterrole-cert-manager-controller-ingress-shim.yaml
- clusterrole-cert-manager-controller-issuers.yaml
- clusterrole-cert-manager-controller-orders.yaml
- clusterrole-cert-manager-edit.yaml
- clusterrole-cert-manager-view.yaml
- clusterrole-cert-manager-webhook:subjectaccessreviews.yaml
- clusterrolebinding-cert-manager-cainjector.yaml
- clusterrolebinding-cert-manager-controller-approve:cert-manager-io.yaml
- clusterrolebinding-cert-manager-controller-certificates.yaml
- clusterrolebinding-cert-manager-controller-certificatesigningrequests.yaml
- clusterrolebinding-cert-manager-controller-challenges.yaml
- clusterrolebinding-cert-manager-controller-clusterissuers.yaml
- clusterrolebinding-cert-manager-controller-ingress-shim.yaml
- clusterrolebinding-cert-manager-controller-issuers.yaml
- clusterrolebinding-cert-manager-controller-orders.yaml
- clusterrolebinding-cert-manager-webhook:subjectaccessreviews.yaml
- customresourcedefinition-certificaterequests.cert-manager.io.yaml
- customresourcedefinition-certificates.cert-manager.io.yaml
- customresourcedefinition-challenges.acme.cert-manager.io.yaml
- customresourcedefinition-clusterissuers.cert-manager.io.yaml
- customresourcedefinition-issuers.cert-manager.io.yaml
- customresourcedefinition-orders.acme.cert-manager.io.yaml
- deployment-cert-manager-cainjector.yaml
- deployment-cert-manager-webhook.yaml
- deployment-cert-manager.yaml
- mutatingwebhookconfiguration-cert-manager-webhook.yaml
- namespace-cert-manager.yaml
- role-cert-manager-cainjector:leaderelection.yaml
- role-cert-manager-tokenrequest.yaml
- role-cert-manager-webhook:dynamic-serving.yaml
- role-cert-manager:leaderelection.yaml
- rolebinding-cert-manager-cainjector:leaderelection.yaml
- rolebinding-cert-manager-tokenrequest.yaml
- rolebinding-cert-manager-webhook:dynamic-serving.yaml
- rolebinding-cert-manager:leaderelection.yaml
- service-cert-manager-cainjector.yaml
- service-cert-manager-webhook.yaml
- service-cert-manager.yaml
- serviceaccount-cert-manager-cainjector.yaml
- serviceaccount-cert-manager-webhook.yaml
- serviceaccount-cert-manager.yaml
- validatingwebhookconfiguration-cert-manager-webhook.yaml
