kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cryoem-logbook--exp
spec:
  storageClassName: cryoem-logbook-prod--exp
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-logbook-dev--exp
  labels:
    type: local
spec:
  storageClassName: cryoem-logbook-dev--exp
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /gpfs/slac/cryo/fs1/exp/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage/cryoem
          operator: In
          values:
          - 'true'
