namespace: cryoem-logbook-dev

bases:
- ../../base/

resources:
- ns.yaml
- database-storage.yaml
- ingress.yaml
- cryoem-storage.yaml
- message_bus-storage.yaml

patchesStrategicMerge:
- storage-patches.yaml
- logbook-patches.yaml
#- nodeSelector-patches.yaml
- message_bus-patches.yaml
#- collab-listener-patches.yaml
- rbac.yaml

secretGenerator:
- name: mongodb
  literals:
  - username=admin
  - password=somepassword
- name: explgbk-writer
  literals:
  - username=writer
  - password=somepassword
- name: explgbk-reader
  literals:
  - username=reader
  - password=somepassword
- name: auth-secrets
  files:
  - ./cert.crt
  - ./intermediates.cer
  - ./cert.key
  - ./keytab_webauth
  - ./backend.htpasswd

images:
- name: slaclab/explgbk-docker
  #newTag: '20201106.0'
  newTag: "20201124.0"
- name: slaclab/explgbk-collab-listener
  newTag: '20201019.1'

