apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ns.yaml
- resources/clusterrole-cert-manager-cainjector.yaml
- resources/clusterrole-cert-manager-cluster-view.yaml
- resources/clusterrole-cert-manager-controller-approve:cert-manager-io.yaml
- resources/clusterrole-cert-manager-controller-certificates.yaml
- resources/clusterrole-cert-manager-controller-certificatesigningrequests.yaml
- resources/clusterrole-cert-manager-controller-challenges.yaml
- resources/clusterrole-cert-manager-controller-clusterissuers.yaml
- resources/clusterrole-cert-manager-controller-ingress-shim.yaml
- resources/clusterrole-cert-manager-controller-issuers.yaml
- resources/clusterrole-cert-manager-controller-orders.yaml
- resources/clusterrole-cert-manager-edit.yaml
- resources/clusterrole-cert-manager-view.yaml
- resources/clusterrole-cert-manager-webhook:subjectaccessreviews.yaml
- resources/clusterrolebinding-cert-manager-cainjector.yaml
- resources/clusterrolebinding-cert-manager-controller-approve:cert-manager-io.yaml
- resources/clusterrolebinding-cert-manager-controller-certificates.yaml
- resources/clusterrolebinding-cert-manager-controller-certificatesigningrequests.yaml
- resources/clusterrolebinding-cert-manager-controller-challenges.yaml
- resources/clusterrolebinding-cert-manager-controller-clusterissuers.yaml
- resources/clusterrolebinding-cert-manager-controller-ingress-shim.yaml
- resources/clusterrolebinding-cert-manager-controller-issuers.yaml
- resources/clusterrolebinding-cert-manager-controller-orders.yaml
- resources/clusterrolebinding-cert-manager-webhook:subjectaccessreviews.yaml
- resources/deployment-cert-manager-cainjector.yaml
- resources/deployment-cert-manager-webhook.yaml
- resources/deployment-cert-manager.yaml
- resources/mutatingwebhookconfiguration-cert-manager-webhook.yaml
- resources/role-cert-manager-cainjector:leaderelection.yaml
- resources/role-cert-manager-startupapicheck:create-cert.yaml
- resources/role-cert-manager-tokenrequest.yaml
- resources/role-cert-manager-webhook:dynamic-serving.yaml
- resources/role-cert-manager:leaderelection.yaml
- resources/rolebinding-cert-manager-cainjector:leaderelection.yaml
- resources/rolebinding-cert-manager-cert-manager-tokenrequest.yaml
- resources/rolebinding-cert-manager-startupapicheck:create-cert.yaml
- resources/rolebinding-cert-manager-tokenrequest.yaml
- resources/rolebinding-cert-manager-webhook:dynamic-serving.yaml
- resources/rolebinding-cert-manager:leaderelection.yaml
- resources/service-cert-manager-cainjector.yaml
- resources/service-cert-manager-webhook.yaml
- resources/service-cert-manager.yaml
- resources/serviceaccount-cert-manager-cainjector.yaml
- resources/serviceaccount-cert-manager-startupapicheck.yaml
- resources/serviceaccount-cert-manager-webhook.yaml
- resources/serviceaccount-cert-manager.yaml
- resources/servicemonitor-cert-manager.yaml
- resources/validatingwebhookconfiguration-cert-manager-webhook.yaml
- jobs/job-cert-manager-startupapicheck.yaml
