FROM python:3.6-alpine

RUN apk update && apk add --no-cache python3 librdkafka acl \
    && pip install kafka requests

ADD collab-listener.py /collab-listener.py

ENTRYPOINT ["python","/collab-listener.py"]
