# Source: psmdb-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psmdb-operator
  namespace: psmdb-operator
  labels:
    app.kubernetes.io/name: psmdb-operator
    helm.sh/chart: psmdb-operator-1.22.0
    app.kubernetes.io/instance: psmdb-operator
    app.kubernetes.io/version: "1.22.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: psmdb-operator
      app.kubernetes.io/instance: psmdb-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: psmdb-operator
        app.kubernetes.io/instance: psmdb-operator
    spec:
      serviceAccountName: psmdb-operator
      securityContext:
        {}
      containers:
        - name: psmdb-operator
          securityContext:
            {}
          image: "percona/percona-server-mongodb-operator:1.22.0"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
            protocol: TCP
            name: metrics
          - containerPort: 8081
            protocol: TCP
            name: health
          command:
          - percona-server-mongodb-operator
          env:
            - name: LOG_STRUCTURED
              value: "false"
            - name: LOG_LEVEL
              value: "INFO"
            - name: WATCH_NAMESPACE
              value: "dev"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: percona-server-mongodb-operator
            - name: RESYNC_PERIOD
              value: "5s"
            - name: DISABLE_TELEMETRY
              value: "false"
            - name: MAX_CONCURRENT_RECONCILES
              value: "1"
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
          readinessProbe:
            httpGet:
              path: /healthz
              port: health
          resources:
            {}
