---

apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    name: auth


#---
#
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: cryoem-logbook--expdata
#spec:
#  storageClassName: cryoem-logbook--expdata
#  accessModes:
#    - ReadOnlyMany
#  resources:
#    requests:
#      storage: 1Gi


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1 
  selector:
    matchLabels:
      name: auth
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: auth
    spec:
      containers:
        - name: auth
          image: slaclab/explgbk-auth:20190430.0
          ports:
            - containerPort: 443
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: 433 
          #  initialDelaySeconds: 10
          #  periodSeconds: 10
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: 433
          #  initialDelaySeconds: 30
          #  periodSeconds: 10
          env:
            # - name: FAKE_AUTH
            #   value: "1"
            # - name: FAKE_AUTH_USER
            #   value: "ytl"
            - name: REQUIRE_VALID_USER
              value: "1"
            - name: USE_WEBAUTH
              value: "1"
            ###
            # server
            ###
            - name: WEBAUTH_LOGIN_URL
              value: https://webauth.slac.stanford.edu/login/
            - name: WEBAUTH_WEBKDC_URL
              value: https://webauth.slac.stanford.edu/webkdc-service/ 
            - name: SERVER_NAME
              value: cryoem-logbook-dev.slac.stanford.edu
            - name: SERVER_ADMIN
              value: cryoem@slac.stanford.edu
            - name: PROXY_HOST
              value: explgbk
            - name: HTTPS_REDIRECT
              value: http://www/
          volumeMounts:
            - name: auth-secrets
              mountPath: /etc/httpd/certs/
            - name: auth-exp-data
              mountPath: /expdata/
            - name: auth-configmap
              mountPath: /etc/httpd/conf.d/explgbk.conf
              subPath: explgbk.conf
        - name: telegraf
          image: docker.io/telegraf:1.13.2
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          env:
            - name: ENVIRONMENT
              value: dev
            - name: MONITOR_HOST
              value: https://influxdb.slac.stanford.edu:443
            - name: MONITOR_DATABASE
              value: cryoem-logbook
          volumeMounts:
          - name: telegraf-config
            mountPath: /etc/telegraf
          #env:
          #- name: HOSTNAME
          #  valueFrom:
          #    fieldRef:
          #      fieldPath: spec.nodeName
      volumes:
        - name: auth-secrets
          secret:
            secretName: auth-secrets
            items:
              - key: cert.crt
                path: cert.crt
              - key: cert.key
                path: cert.key
              - key: keytab_webauth
                path: keytab_webauth
              - key: backend.htpasswd
                path: backend.htpasswd
              - key: intermediates.cer
                path: intermediates.cer
        - name: auth-exp-data
          emptyDir: {}
 #         persistentVolumeClaim:
 #           claimName: cryoem-logbook--expdata
        - name: auth-configmap
          configMap:
            name: auth-config
            items:
              - key: explgbk.conf
                path: explgbk.conf
        - name: telegraf-config
          configMap:
            name: telegraf-apache
