namespace: cryoem-logbook

resources:
- logbook.yaml
- auth.yaml
- collab-listener.yaml

configMapGenerator:
- name: auth-config 
  files:
  - explgbk.conf
- name: telegraf-apache
  files:
  - telegraf.conf=telegraf-apache.conf
- name: telegraf-gunicorn
  files:
  - telegraf.conf=telegraf-gunicorn.conf
- name: telegraf-mongodb
  files:
  - telegraf.conf=telegraf-mongodb.conf

#secretGenerator:
#- name: mongo
#  literals:
#  - username=admin
#  - password=somepassword
#- name: explgbk-writer
#  literals:
#  - username=writer
#  - password=somepassword
#- name: explgbk-reader
#  literals:
#  - username=reader
#  - oasswird=somepassword
#- name: auth-secrets
#  literals:
#  - cert.crt=TBD
#  - cert.key=TBD
#  - keytab_webauth=TBD
#  - backend.htpasswd=TBD

