apiVersion: apps/v1
kind: Deployment
metadata:
  name: collab-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collab-listener
  template:
    metadata:
      labels:
        app: collab-listener
    spec:
      securityContext:
        runAsUser: 15693
        runAsGroup: 3591
      containers:
      - name: collab-listener
        image: slaclab/explgbk-collab-listener:20200421.0
        imagePullPolicy: Always
        env:
        - name: KAFKA_BOOTSTRAP_SERVER
          value: kafka:9092
        - name: KAFKA_TOPIC
          value: roles
        - name: KAFKA_GROUP_ID
          value: roles
      volumes:
      - name: exp-data
        persistentVolumeClaim:
          claimName: cryoem-logbook--sdf-exp
