kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fs-ddn-sdf-group-cryoem-exp
spec:
  storageClassName: fs-ddn-sdf-group-cryoem-exp
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi

---
