kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-logbook-prod--mongo-0
  labels:
    type: local
spec:
  storageClassName: cryoem-logbook-prod--mongo
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /gpfs/slac/cryo/fs1/daq/prod/mongo/mongo-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage/cryoem
          operator: In
          values:
          - 'true'

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-logbook-prod--mongo-2
  labels:
    type: local
spec:
  storageClassName: cryoem-logbook-prod--mongo
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /gpfs/slac/cryo/fs1/daq/prod/mongo/mongo-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage/cryoem
          operator: In
          values:
          - 'true'

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-logbook-prod--mongo-1
  labels:
    type: local
spec:
  storageClassName: cryoem-logbook-prod--mongo
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/cryoem-logbook-prod/daq/prod/mongo/mongo-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - os-ctrl01

