namespace: cryoem-logbook

bases:
- ../../operators/
- ../../base/

resources:
- ns.yaml
- mongo-database.yaml
- kafka-messagebus.yaml
- ingress.yaml

patchesStrategicMerge:
- auth-patches.yaml
- logbook-patches.yaml
- collab-listener-patches.yaml

secretGenerator:
- name: mongodb
  literals:
  - username=admin
  - password=somepassword
- name: explgbk-writer
  literals:
  - username=writer
  - password=somepassword
- name: explgbk-reader
  literals:
  - username=reader
  - password=somepassword
- name: auth-secrets
  files:
  - ./etc/.secrets/cert.crt
  - ./etc/.secrets/intermediates.cer
  - ./etc/.secrets/cert.key
  - ./etc/.secrets/keytab_webauth
  - ./etc/.secrets/backend.htpasswd
- name: collab-listener
  literals:
  - username=cryo-daq
  files:
  - password=./etc/.secrets/collab-listener.password

images:
- name: slaclab/explgbk-docker
#  newTag: '20201210.0'
  newTag: '20220121.0'
- name: slaclab/explgbk-collab-listener
  newTag: '20201019.1'
