namespace: cryoem-logbook-prod

bases:
- ../../base/

resources:
- ns.yaml
- database-storage.yaml
- ingress.yaml
- cryoem-storage.yaml
- rbac.yaml

patchesStrategicMerge:
- auth-patches.yaml
- storage-patches.yaml
- logbook-patches.yaml
- collab-listener-patches.yaml
#- nodeSelector-patches.yaml

secretGenerator:
- name: mongodb
  literals:
  - username=admin
  - password=somepassword
- name: explgbk-writer
  literals:
  - username=writer
  - password=somepassword
- name: explgbk-reader
  literals:
  - username=reader
  - password=somepassword
- name: auth-secrets
  files:
  - ./etc/cert.crt
  - ./etc//intermediates.cer
  - ./etc/cert.key
  - ./etc/keytab_webauth
  - ./etc/backend.htpasswd
- name: collab-listener
  literals:
  - username=cryo-daq
  files:
  - password=./etc/collab-listener.password

images:
- name: slaclab/explgbk-docker
  #newTag: '20200525.0'
  newTag: '20201008.0'
- name: slaclab/explgbk-collab-listener
  newTag: "20200501.1"
