---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: explgbk
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: explgbk
        env:
          - name: LOGBOOK_SITE
            value: CryoEM
          - name: URAWI_EXPERIMENT_LOOKUP_URL
            value: https://userportal.slac.stanford.edu/apps/urawi/ws/cryo_btsr_info
          - name: NODE_ENV
            value: prod
          - name: MONGODB_URL
            value: 'mongodb://mongo-rs0-0.mongo-rs0:27017,mongo-rs0-1.mongo-rs0:27017,mongo-rs0-2.mongo-rs0:27017/?replicaSet=rs0'
            #value: mongodb://mongo-mongos:27017
          - name: KAFKA_BOOTSTRAP_SERVER
            value: kafka-kafka-bootstrap:9092

