---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafka-node-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: cryoem-logbook-prod


---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafka-pod-labler
  namespace: kafka
subjects:
- kind: ServiceAccount
  name: default
  namespace: cryoem-logbook-prod

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
         storage: 1Gi
      storageClassName: cryoem-logbook-prod--kafka

