kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-logbook-prod--kafka-0
  labels:
    type: local
spec:
  storageClassName: cryoem-logbook-prod--kafka
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/cryoem-logbook-prod/daq/prod/kafka/kafka-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - neb0002.slac.stanford.edu

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-logbook-prod--kafka-2
  labels:
    type: local
spec:
  storageClassName: cryoem-logbook-prod--kafka
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/cryoem-logbook-prod/daq/prod/kafka/kafka-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - deft0029

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cryoem-logbook-prod--kafka-1
  labels:
    type: local
spec:
  storageClassName: cryoem-logbook-prod--kafka
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/cryoem-logbook-prod/daq/prod/kafka/kafka-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - os-ctrl01

