apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: mongo
  namespace: cryoem-logbook
spec:
  crVersion: 1.22.0
  #backup:
  #  enabled: true
  #  image: percona/percona-backup-mongodb:2.9.1
  #  pitr:
  #    compressionLevel: 6
  #    compressionType: gzip
  #    enabled: true
  #  serviceAccountName: percona-server-mongodb-operator
  #  storages:
  #    minio:
  #      s3:
  #        bucket: cryoem-logbook-mongodb-backup
  #        credentialsSecret: mongo-backup-s3-2mmtk52f47
  #        endpointUrl: https://s3dfrgw.slac.stanford.edu
  #        region: Default
  #      type: s3
  image: percona/percona-server-mongodb:6.0.27-21
  pause: false
  replsets:
  - affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    configuration: |
      storage:
        wiredTiger:
          engineConfig:
            cacheSizeGB: 16
          collectionConfig:
            blockCompressor: snappy
          indexConfig:
            prefixCompression: true
    containerSecurityContext:
      capabilities:
        add:
        - SYS_RESOURCE
      privileged: false
    livenessProbe:
      failureThreshold: 10
      initialDelaySeconds: 7200
      periodSeconds: 360
      startupDelaySeconds: 7200
      timeoutSeconds: 10
    name: rs0
    readinessProbe:
      failureThreshold: 10
      initialDelaySeconds: 3
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "16"
        memory: 64Gi
      requests:
        cpu: "8"
        memory: 32Gi
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 100Gi
  secrets:
    users: cryoem-logbook
  sharding:
    configsvrReplSet:
      configuration: |
        storage:
          wiredTiger:
            engineConfig:
              cacheSizeGB: 2
      containerSecurityContext:
        capabilities:
          add:
          - SYS_RESOURCE
      livenessProbe:
        failureThreshold: 10
        initialDelaySeconds: 120
        periodSeconds: 30
        startupDelaySeconds: 7200
        timeoutSeconds: 30
      readinessProbe:
        failureThreshold: 10
        initialDelaySeconds: 3
        periodSeconds: 30
        timeoutSeconds: 10
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
        requests:
          cpu: "1"
          memory: 4Gi
      size: 3
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
    enabled: true
    mongos:
      livenessProbe:
        failureThreshold: 6
        initialDelaySeconds: 60
        periodSeconds: 30
        timeoutSeconds: 10
      readinessProbe:
        failureThreshold: 8
        initialDelaySeconds: 3
        periodSeconds: 10
        timeoutSeconds: 5
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 2Gi
      size: 3
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: disabled
    schedule: 0 2 * * *
    setFCV: false
