apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: mongo-dev
  namespace: dev
spec:
  backup:
    enabled: true
    image: percona/percona-backup-mongodb:2.12.0
    pitr:
      compressionLevel: 6
      compressionType: gzip
      enabled: true
    #serviceAccountName: percona-server-mongodb-operator
    tasks:
    - name: nightly-physical-backup
      schedule: "0 3 * * *"
      keep: 7
      storageName: minio
      type: physical
      compressionType: gzip
      compressionLevel: 6
    storages:
      minio:
        s3:
          bucket: cryoem-logbook-mongodb-backup
          credentialsSecret: mongo-backup-s3
          endpointUrl: https://s3dfrgw.slac.stanford.edu
          region: Default
        type: s3
