apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDBBackup
metadata:
  name: full-logical-backup-mongo-20260505
  namespace: dev
spec:
  clusterName: mongo
  storageName: minio
  #type: physical
  type: logical
