---
# Source: psmdb-operator/templates/role-binding.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-operator-psmdb-operator
---
# Source: psmdb-operator/templates/role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-operator-psmdb-operator
  labels:
    app.kubernetes.io/name: psmdb-operator
    helm.sh/chart: psmdb-operator-1.12.0
    app.kubernetes.io/instance: mongodb-operator
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
    - psmdb.percona.com
    resources:
    - perconaservermongodbs
    - perconaservermongodbs/status
    - perconaservermongodbbackups
    - perconaservermongodbbackups/status
    - perconaservermongodbrestores
    - perconaservermongodbrestores/status
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/exec
    - services
    - persistentvolumeclaims
    - secrets
    - configmaps
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - apps
    resources:
    - deployments
    - replicasets
    - statefulsets
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - batch
    resources:
    - cronjobs
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - policy
    resources:
    - poddisruptionbudgets
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
  - apiGroups:
    - certmanager.k8s.io
    - cert-manager.io
    resources:
    - issuers
    - certificates
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
    - deletecollection
  - apiGroups:
    - net.gke.io
    - multicluster.x-k8s.io
    resources:
    - serviceexports
    - serviceimports
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
    - deletecollection
---
# Source: psmdb-operator/templates/role-binding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-account-mongodb-operator-psmdb-operator
  labels:
    app.kubernetes.io/name: psmdb-operator
    helm.sh/chart: psmdb-operator-1.12.0
    app.kubernetes.io/instance: mongodb-operator
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: mongodb-operator-psmdb-operator
roleRef:
  kind: Role
  name: mongodb-operator-psmdb-operator
  apiGroup: rbac.authorization.k8s.io
---
# Source: psmdb-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-operator-psmdb-operator
  labels:
    app.kubernetes.io/name: psmdb-operator
    helm.sh/chart: psmdb-operator-1.12.0
    app.kubernetes.io/instance: mongodb-operator
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: psmdb-operator
      app.kubernetes.io/instance: mongodb-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: psmdb-operator
        app.kubernetes.io/instance: mongodb-operator
    spec:
      serviceAccountName: mongodb-operator-psmdb-operator
      containers:
        - name: psmdb-operator
          image: "percona/percona-server-mongodb-operator:1.12.0"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 60000
            protocol: TCP
            name: metrics
          command:
          - percona-server-mongodb-operator
          env:
            - name: WATCH_NAMESPACE
              value: cryoem-logbook
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: percona-server-mongodb-operator
            - name: RESYNC_PERIOD
              value: "5s"
            - name: LOG_VERBOSE
              value: "false"
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: metrics
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: metrics
          resources:
            {}
