apiVersion: apps/v1
kind: Deployment
metadata:
  name: psmdb-operator
spec:
  template:
    spec:
      containers:
        - name: psmdb-operator
          env:
            - name: WATCH_NAMESPACE
              value: "cryoem-logbook"
              valueFrom: null
